### ISSUE TITLE
non-developer testing question

### ISSUE THREAD

**Issue by caj411** [jellyfin-archive/jellyfin-roku-original#16]
I have a Roku 3 and I've installed the code, seems to work, except I cannot login. I just stumbled across this and gave it a shot, is it complete or still a work in progress?

**Comment by anthonylavado** [comment]
It’s technically still a work in Progress. Are you using 10.4.1? Did you have an install before?

It could be the baseurl thing. I don’t think this client has been updated for that yet.

You could try adding /Jellyfin at the end of your server entry.

**Comment by dkanada** [comment]
I wonder if this was archived before the password changes.

**Comment by anthonylavado** [comment]
OH. I totally missed that this is original. @caj411  you want to head over to https://github.com/jellyfin/jellyfin-roku

This is the old archived code.

**Comment by caj411** [comment]
> OH. I totally missed that this is original. @caj411 you want to head over to https://github.com/jellyfin/jellyfin-roku
> 
> This is the old archived code.

Thank you. Your response is greatly appreciated!
