### ISSUE TITLE
Remove Active Supporter check

### ISSUE THREAD

**Issue by nZambi-** [jellyfin-archive/jellyfin-roku-original#2]
Active Supporter is only checked before creating Live Tv Guide Screen. It can be easily bypassed (return True) or removed all together... If there will never be a check like this in future versions of the Roku App, it should probably just be removed. (I'll be removing it in my fork I think) Comments?

**Comment by andrewrabert** [comment]
Removing it would be ideal, but a bypass is also great. Looking forward to you opening a pull request! 😀

**Comment by nZambi-** [comment]
Thanks... I'm taking some time to really dig through this thing. I have quite a bit of the Branding Text cleaned up already. I created some graphics for my own install (just HAD to get rid of the green) but will obviously need to wait for the team to decide on Logo design before committing anything there. I'm hoping that Purple wins the day there. This app is certainly not quite ready for prime time. I think after the basic Branding change we'll need to decide on a direction for it.

**Comment by JustAMan** [comment]
@nZambi- I suggest you not wait till you're done with the app completely, reviewing a PR of hundreds of files is a nightmare. Please send them in meaningful chunks!

**Comment by nZambi-** [comment]
@JustAMan I understand.  I'm away from my device but was planing on doing a PR on just the Active Supporter removal after proper testing later this morning. The branding text would be following and graphics are just for me until some Design choices are made by the group. However I got bogged down during my stroll through the code with the amount of issues I have been finding re: depreciated code. (see my latest issue) #3  A bit overwhelming and makes some of the rest of this seem insignificant at the moment... maybe...

**Comment by nZambi-** [comment]
The PR did not seem to break anything... I'll go ahead and close this one...
