### ISSUE TITLE
Replacing Images

### ISSUE THREAD

**Issue by ghost** [jellyfin-archive/jellyfin-roku-original#8]
Replace images/channel/themes/defualt/hd-connectsignin.jpg
Replace images/channel/hd-*.png

Not Sure if there is a standard for the hd, sd images they all show up as different sizes i will have to investigate if jellyfin already has these standards/images

**Comment by anthonylavado** [comment]
If you need any images at sizes that don’t exist in Jellyfin-UX, just let me know and I will get it made for you.

**Comment by ghost** [comment]
I'm not much of a image wiz, but i am looking for something like these : 

![hd-home-tile](https://user-images.githubusercontent.com/17482298/52074072-0eab4a80-2557-11e9-8ec9-af5c1befcb94.png)
![hd-side-tile](https://user-images.githubusercontent.com/17482298/52074073-0eab4a80-2557-11e9-9bef-729dc367393f.png)
![hd-splash](https://user-images.githubusercontent.com/17482298/52074074-0eab4a80-2557-11e9-85f5-6b8038b9aa59.png)
![sd-home-tile](https://user-images.githubusercontent.com/17482298/52074075-0eab4a80-2557-11e9-929f-d8b94dd8d909.png)
![sd-side-tile](https://user-images.githubusercontent.com/17482298/52074076-0eab4a80-2557-11e9-8db4-652a3bc5f8b8.png)
![sd-splash](https://user-images.githubusercontent.com/17482298/52074077-0eab4a80-2557-11e9-89c9-e62461829e09.png)

In the project they are labeled like so, 
![image](https://user-images.githubusercontent.com/17482298/52074461-ea03a280-2557-11e9-8f2d-90afdea57f7b.png)


I saw that jellyfin-ux has some large images, but I cant find any specification on the roku-dev site on what size these are. If you could remake these or some one else? I'm not quiet sure what specifications to give you, sorry.

**Comment by anthonylavado** [comment]
@winters-brown I’ll grab the sizes of these files and create replacements.

**Comment by ghost** [comment]
Any updates on these replacements @anthonylavado ? No rush if not

**Comment by anthonylavado** [comment]
Gonna close as Bisby’s refactor effort has created images, and we’re likely to go with that once ready.
